name: Working Group Proposal
description: Propose a new Working Group to the AAIF Technical Committee.
title: "[Working Group Proposal]:"
labels:
  - new

name: Working Group Proposal
description: Propose a new Working Group to the AAIF Technical Committee.
title: "[Working Group Proposal] <ADD Proposed Name> "
labels: [New]
assignees:
  - christinaharter

body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in forming a working group.

        Please complete the form below to help the AAIF Technical Committee (TC) evaluate your request.

  - type: input
    attributes:
      label: Proposed Working Group Name
      description: "The proposed name of the working group."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Working Group Summary
      description: "Provide a one-line summary of the working group."
      placeholder: "A short, clear summary (max one sentence)"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Working Group Description
      description: "Describe in detail the challenge(s) the working group will try to solve, its potential mission, and key scope areas that the working group will focus on."
    validations:
      required: true

  - type: input
    attributes:
      label: Name of AAIF Member Organization
      description: "Please provide the name of your company or organization. Please note that new Working Groups can only be proposed by AAIF Member companies."
    validations:
      required: true
      
  - type: input
    attributes:
      label: Submitter Information
      description: "Please provide your name, GitHub handle, and business email associated with an AAIF member company."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed Working Group Chair(s)
      description: "Please provide the name(s), GitHub handle(s) and company affiliation for your proposed working group chair(s). Please note that Working Group Chairs must be from either a Platinum or Gold Member company."
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: List of Supporters
      description: "Please provide the name(s), GitHub handle(s) and company affiliation for additional supporters of this working group. Please ensure they are from a different member company than the submitter."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Information
      description: "Any other details the TC should know when reviewing this proposal."
    validations:
      required: false
